version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:14.15.1
commands:
  restore_modules:
    steps:
      - restore_cache:
          key: dependencies-cache-{{ checksum "package.json" }}
  save_modules:
    steps:
      - save_cache:
          key:  dependencies-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: install dependencies
          command: npm install
      - save_modules
  test:
    executor: node
    steps:
      - checkout
      # - restore_modules
      - run: 
          name: install dependencies
          command: npm install
      - run: pwd
      - run: ls
      - run: 
          name: unit test
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test