version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - restore_cache:
          key: dependencies-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - restore_cache:
          key: dependencies-cache-{{ checksum "package.json" }}
      - run: 
          name: install dependencies
          command: npm install
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test